server:
  port: 8080
spring:
  datasource:
    username: root
    password: wkx123
    url: jdbc:mysql://localhost:3306/bootplus?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    port: 6379
    host: localhost
    password: wkx123
    timeout: 5000
    jedis:
      # 连接池配置  连接池主要作用就是进行连接的缓冲，避免重复创建和销毁连接对象，提高性能
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（负值表示没有限制）
        max-wait: -1
        # 连接池最大空闲连接
        max-idle: 8
        # 连接池最小空闲连接
        min-idl: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
